hivemapper:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dev
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5433
      dbname: hivemapper
      schema: hivemapper
    prod:
      type: postgres
      host: localhost
      user: dev
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5433
      dbname: hivemapper
      schema: hivemapper

  target: dev
